### ISSUE TITLE
Replace react-toolbox snackbacr with a 3rd party notif. library

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#123]

**Comment by PSilling** [comment]
Ok, I'd vote for this: https://github.com/minhtranite/react-notifications. I think it matches our UI quite well.

**Comment by sbunciak** [comment]
Looks good to me.

**Comment by sbunciak** [comment]
Fixed by https://github.com/StudentHubCZ/studenthub-portal/commit/05b82772dcdf4265b4899e2ac571af0abdf34109
