### ISSUE TITLE
Workflow change: allow only student signUp

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#128]
We would introduce a new role: university ambassador which would add ac.supervisors

**Comment by TheSprtCz** [comment]
Probably part of #7, because we have to create some way for ambassador to create ac.supervisors. Also we should allow company reps to create tech leaders.

**Comment by sbunciak** [comment]
@TheSprtCz just a note: currently, company reps are creating tech leaders for their company, so I guess no change there.
