### ISSUE TITLE
Paging throws error at last page

### ISSUE THREAD

**Issue by PSilling** [StudentHubCZ/studenthub-portal#148]

**Comment by sbunciak** [comment]
This might be a non-resolvable issue, after all. Reading through various threads/blog posts it seems that no matter what we do if server responds with 404 (which is a desired response in our case) browser will log an error to its console...

**Comment by PSilling** [comment]
I also believe that's the case. But on the other hand I think that in the future we could, actually even should as this system is imo pretty bad, introduce proper paging with selectable pages, not just Next/Prev. https://github.com/AdeleD/react-paginate looked promising to me.
