### ISSUE TITLE
Deleting a user referenced company throws 500

### ISSUE THREAD

**Issue by PSilling** [StudentHubCZ/studenthub-portal#162]
The error is as far as I know caused by users having references to that certain company as the references aren't removed beforehand.

**Comment by TheSprtCz** [comment]
I think this is expected behaviour. In current design if company was removed from for example TECH_LEADER it would cause bunch of other problems in TopicResource. WDYT @sbunciak ?

**Comment by sbunciak** [comment]
I agree with @TheSprtCz. You can't remove a company with users associated to it. That might render COMPANY_REP or TECH_LEADER without a company and that wouldn't be a desirable state.
