### ISSUE TITLE
Sending a PUT or POST company request throws error 500

### ISSUE THREAD

**Issue by PSilling** [StudentHubCZ/studenthub-portal#163]
There seems to be some kind of null mismatch caused by CompanyPlan. Could possibly be an issue in my current UI build, not sure.
Anyway, the tested plan in sent Company resource was set as follows:
`plan: { 
"name" : "String",
"description" : "String",
"maxTopics" : 10 
}`

**Comment by TheSprtCz** [comment]
Did a little bit of testing, this is actually ok behaviour. CompanyPlan is independent entity which means it needs to be created beforehand. That 500 error is `TransientPropertyValueException` which basically mean that you tried to send not existing CompanyPlan (CompanyPlan that wasn’t saved before). Correct way how to send CompanyPlan with initial data is this:
`plan: { "name" : "TIER_1" }`

**Comment by PSilling** [comment]
Ok, will look into it...
