### ISSUE TITLE
Delete and update endpoints throw error when non-existent id is supplied

### ISSUE THREAD

**Issue by TheSprtCz** [StudentHubCZ/studenthub-portal#27]
When you try update or delete anything with non-existent id for example **[DELETE] /api/universities/158** it throws error, because hibernate will try updating something which does not exist.

**Comment by sbunciak** [comment]
Fixed in https://github.com/StudentHubCZ/studenthub-portal/commit/52b728d12b15b4025948754492dfd9b5020874a8
