### ISSUE TITLE
Investigate possibility of using react-jwt-auth

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#43]
https://github.com/fullstackforger/react-jwt-auth

**Comment by sbunciak** [comment]
if we are not going to use it we should at least store JWT token in local storage instead of cookies

**Comment by sbunciak** [comment]
@PSilling could you please look into this?

**Comment by PSilling** [comment]
@sbunciak I will see what I can do, but before wednesday I may only be able to look into their documentation tbh.

**Comment by sbunciak** [comment]
This won't be necessary.
