### ISSUE TITLE
Cannot create Topic due to missing creator

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#60]
Creator field is first checked for creator before creator is assigned.

**Comment by TheSprtCz** [comment]
I see a few solutions to this problem:
1) Remove @NotNull from creator and leave nullable=false in changelog.
   * Would result in Hibernate and Liquibase generating different DB schemes.
2) Drop the idea of automatically assigning creator.
   * You will have to send creator in request body.
   * There will be permission check for if creating topic with different creator than currently logged in.
3) Revert #53.

**Comment by sbunciak** [comment]
I prefer 2nd solution
