### ISSUE TITLE
Paging of topics returns all elements when filter exceeds size

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#61]
E.g. having less then 20 topics in DB the following request returns entire collection. http://localhost:3000/topics?size=10&start=20

**Comment by sbunciak** [comment]
I really don't think it's correct. It should either return 0 results, or error, similar to https://docs.oracle.com/javase/7/docs/api/java/util/List.html#subList(int,%20int)

**Comment by TheSprtCz** [comment]
Ok, what kind of error response would be best? I suggest Bad Request or Not Acceptable. Also should I include some kind of body to the error saying what went wrong or leave it plain?

**Comment by sbunciak** [comment]
Bag Request sounds good. Body is not necessary, I'd say. What would you put there?

**Comment by TheSprtCz** [comment]
You cannot have start bigger than size of collection.

Anyway, I suggest throwing error only when start is bigger than collection size, and rename size to maxSize and if there are not enough entries then just return what is remaining.

**Comment by sbunciak** [comment]
> Anyway, I suggest throwing error only when start is bigger than collection size, and rename size to maxSize and if there are not enough entries then just return what is remaining.

@TheSprtCz that makes sense.
