### ISSUE TITLE
PUT /users fails with 422 due to missing password field

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#64]
@TheSprtCz  any ideas how to solve it?

**Comment by TheSprtCz** [comment]
This problem can probably be solved only by removing @NotEmpty at password field, but this will have consequences as it would no longer be required to send password when registering. So I suggest to split registration process into 2 parts: Registering without password & Activation with setting password.

**Comment by sbunciak** [comment]
+1 to your suggestion. User will get 'activated' once he set a password.

**Comment by sbunciak** [comment]
@TheSprtCz I'll take care of this.

**Comment by PSilling** [comment]
It's also a problem in an another way. When a user account is edited at least once, it becomes impossible to log into that account again as POST `/auth/login` returns 401.

**Comment by TheSprtCz** [comment]
That makes sense, you have to sent password in request but update method doesnt transform it in any way so it is probably saving whatever you sent in password field and you won't be able to log in.
