### ISSUE TITLE
Support GET request search for /universities and /universities/{id}/faculties

### ISSUE THREAD

**Issue by PSilling** [StudentHubCZ/studenthub-portal#65]

**Comment by TheSprtCz** [comment]
@sbunciak I suggest either using same method as we use in Topic, or creating new helper class to make adding more search endpoints easier, WDYT?

**Comment by sbunciak** [comment]
@TheSprtCz would it be very time consuming to create the helper class and refactor Topic search? That would be preferred way of resolving this issue. If it's too 'expensive' we can postpone until next version.

**Comment by TheSprtCz** [comment]
It shouldn't take that much time. Gonna start working on it.
