### ISSUE TITLE
Add field 'visible' to Topic

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#67]
So that topic creator can have topic(s) in some 'draft' state

**Comment by sbunciak** [comment]
+ allow creator to delete his topics without any applications associated

**Comment by TheSprtCz** [comment]
For which endpoints should I implement boolean param to see also "invisible" topics?

**Comment by sbunciak** [comment]
All returning topic(s): 
- ```topics```
- ```topics/{id}```
- ```topics/search```

Do you think any other endpoint should be affected?
Topics in draft state (="invisible") should be visible only to ADMIN and their creator.

**Comment by TheSprtCz** [comment]
Here is complete list of endpoints and my suggestion what to do with them:
* ```topics``` - probably permission check or show only visible.
* ```topics/{id}``` - permission check if they want to show invisible topic. 
* ```topics/search``` - only visible.
* ```companies/{id}/topics``` - only visible.
*  ```tags/{tag}/topics``` - only visible.
* ```users/{id}/supervisedTopics``` - all topic should be displayed.
* ```users/{id}/ownedTopics``` - all topic should be displayed.

**Comment by sbunciak** [comment]
I agree in all cases except ```topics```. We should
 - display all
- secure this endpoint, enable only admin (other users should use either topics/search or users/{id}/...

**Comment by TheSprtCz** [comment]
@sbunciak I don't think that it is good solution, since you have to specify for what you are searching when using `topics/search`. I would rather have there argument `onlyEnabled` and permission check for it.
