### ISSUE TITLE
Integration test sometimes throw TimeoutError

### ISSUE THREAD

**Issue by TheSprtCz** [StudentHubCZ/studenthub-portal#70]
Generally LoginTest fails. Maybe problem with getting token?

**Comment by sbunciak** [comment]
Still happening unfortunately :-/

**Comment by TheSprtCz** [comment]
Caused by Dropwizard client configuration which default timeout to 500ms, which is not enough for less powerful machines. Sadly because `dropwizard-client` is only available in testing I am not able to change these settings in configuration. Investigating other options.
