### ISSUE TITLE
PUT /applications/{id} fails with error 500

### ISSUE THREAD

**Issue by PSilling** [StudentHubCZ/studenthub-portal#72]
Haven't found the reason, but I would assume it may be similar to our previous issues.
Tried to send PUT request with body: `{"officialAssignment":"test"}` to api/applications/3.

**Comment by TheSprtCz** [comment]
I believe this endpoint is acting exactly as is should. When you update something through PUT you have to include all fields, not only those you want to update and Topic Application has 3 required fields that have to be sent in every request: Topic, Faculty & Student.

**Comment by PSilling** [comment]
Welp, when I send to the same endpoint this, it replies with 500:
`{"student":{"id":1},"officialAssignment":"Test","topic":{"id":1},"faculty":{"id":1}}`
Tried even returning with PUT the same JSON recieved from GET request, same error.

**Comment by TheSprtCz** [comment]
I wasn't able to replicate it on my local testing configuration with your exact JSON, and I am not sure what could be causing the problem, since 500 is the most generic error we have. @sbunciak Could you please provide server log, so I can investigate it further?

**Comment by PSilling** [comment]
That is really interesting. I tried sending it through Postman and even the ui-mock itself with the same result (error 500). Is it possible that your local testing config is more up to date than the current api server (138.68.71.187:8080/api/) and has this issue resolved already somehow?

**Comment by TheSprtCz** [comment]
I think that api server is kept up-to-date and think that it will have something to do with DB configuration, since my configuration was precisely crafted to not throw any errors (all required and logical relations are met etc.). I will try to test on your api server.

**Comment by TheSprtCz** [comment]
I think I've succesfully identified the issue, we check if user is AcademicSupervisor or a TechLeader while not requiring them. @sbunciak Do you think that I can simply add these two as required or there do we need to have an ability to create TopicApplication without these two?

**Comment by PSilling** [comment]
Now I've finished (hopefully) working on application task management, but I get error 500 even for GET request sent to endpoint `applications/15/tasks` (other IDs tested also without any success). Tested with admin user and student only user.

**Comment by sbunciak** [comment]
@TheSprtCz Tech Leader should be required, but Academic Supervisor not. We can have applications without Ac. Supervisor assigned.

**Comment by sbunciak** [comment]
@TheSprtCz @PSilling here is the server log from today, containing both exceptions. In both cases its NPE :-( 

https://gist.github.com/sbunciak/8603eaf1021940a473cbef482db227ca

Btw. do you happen to know what might be causing the HttpParser warnings?

**Comment by TheSprtCz** [comment]
I've never seen them in localhost setting, so no clue what so ever, anyway I already created PR #73 to fix this issue.
