### ISSUE TITLE
Create email templates

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#74]
- sign up (activation)
- password update
- topic application updates
- invite user (e.g. company rep invites tech leader)

**Comment by sbunciak** [comment]
@PSilling anything else need to send emails about?

**Comment by PSilling** [comment]
Maybe bug reporting and contacting admin?

**Comment by sbunciak** [comment]
@TheSprtCz wdyt?

**Comment by sbunciak** [comment]
@PSilling both of those would be just simple links (bug report pointing towards github, and contact admin a mailto admin)

**Comment by TheSprtCz** [comment]
I would maybe add Lost password recovery to the list.
